/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          navy: '#0B1E36',
          'navy-dark': '#020E23',
          'navy-light': '#1A2E47',
          terracotta: '#C84B31',
          'terracotta-dark': '#A93100',
          'terracotta-light': '#E05D41',
          orange: '#FF4F00',
          bg: '#F8FAFC',
          surface: '#F7F9FC',
          border: '#E2E8F0',
        },
        // Stitch export tokens
        primary: '#C84B31',
        'primary-container': '#D34000',
        'primary-fixed': '#FFE4DD',
        'primary-fixed-dim': '#FFB59E',
        'on-primary-fixed-variant': '#8A2E18',
        secondary: '#525F77',
        'secondary-fixed': '#E8EDF5',
        'secondary-container': '#D3E0FD',
        'secondary-fixed-dim': '#BAC7E3',
        'on-secondary-fixed': '#1F2A37',
        tertiary: '#4F5D71',
        'tertiary-container': '#67758B',
        'tertiary-fixed': '#D5E3FC',
        'on-surface-variant': '#4B5563',
        surface: '#F7F9FC',
        'surface-variant': '#E0E3E6',
        'surface-container': '#ECEEF1',
        'surface-container-low': '#F2F4F7',
        'surface-container-high': '#E6E8EB',
        'surface-container-highest': '#DCE3EA',
        'surface-container-lowest': '#FFFFFF',
        'on-primary': '#FFFFFF',
        'on-surface': '#191C1E',
        'inverse-on-surface': '#F7F9FC',
        'outline-variant': '#C7CDD4',
        'on-secondary-fixed-variant': '#3B475E',
        error: '#B91C1C',
        // RBAC Role Colors
        role: {
          citizen: '#10B981',
          'citizen-light': '#D1FAE5',
          university: '#6366F1',
          'university-light': '#E0E7FF',
          industry: '#F59E0B',
          'industry-light': '#FEF3C7',
          admin: '#8B5CF6',
          'admin-light': '#EDE9FE',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        geist: ['Geist', 'Inter', 'sans-serif'],
        display: ['Geist', 'Inter', 'sans-serif'],
        'headline-xl': ['Geist', 'Inter', 'sans-serif'],
        'headline-md': ['Geist', 'Inter', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'label-bold': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['2.25rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'headline-md': ['1.5rem', { lineHeight: '1.2', letterSpacing: '-0.015em' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'body-md': ['1rem', { lineHeight: '1.5rem' }],
        'label-bold': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.04em' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.04em' }],
      },
      maxWidth: {
        'max-width': '1440px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '32px',
      },
      boxShadow: {
        'card-shadow': '0 10px 30px rgba(15, 23, 42, 0.08)',
        'custom-shadow': '0 16px 40px rgba(15, 23, 42, 0.12)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleUp: {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.35s ease-out both',
        scaleUp: 'scaleUp 0.2s ease-out both',
      },
    },
  },
  plugins: [],
}
