/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary-container": "#3f5881",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbd0",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#852400",
        "on-primary-fixed": "#3a0b00",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#d6e3ff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-primary": "#ffb59e",
        "on-secondary-fixed-variant": "#2d476f",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#aec7f6",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#66768d",
        "surface-tint": "#ae3200",
        "surface": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "outline-variant": "#e6beb2",
        "secondary": "#465f88",
        "surface-container-highest": "#e1e3e4",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "tertiary": "#4d5d73",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#d43f00",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "primary": "#aa3000",
        "outline": "#916f65",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5c4037",
        "secondary-container": "#b6d0ff",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-background": "#191c1d",
        "on-tertiary-container": "#fdfcff",
        "on-secondary-fixed": "#001b3d",
        "primary-fixed-dim": "#ffb59e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "margin-desktop": "64px",
        "stack-lg": "32px",
        "base": "4px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-bold": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
